name: Flutter Android Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.x"
        channel: "stable"

    - name: Clean the Flutter build files
      run: flutter clean
      working-directory: ./taskii

    - name: Install dependencies
      working-directory: ./taskii
      run: flutter pub get

    - name: Analyze project source
      working-directory: ./taskii
      run: flutter analyze --no-suggestions --no-fatal-warnings --no-fatal-infos

    - name: Run tests
      working-directory: ./taskii
      run: flutter test --coverage

    - name: Build
      working-directory: ./taskii
      run: flutter build apk --release
