name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install CocoaPods
      run: pod install
      working-directory: taskii/ios

    - name: Install dependencies
      run: |
        bundle install
        bundle exec pod install
      working-directory: taskii/ios

    - name: Build the project
      run: |
        xcodebuild -workspace taskii/ios/<YourProjectName>.xcworkspace \
                   -scheme <YourSchemeName> \
                   -sdk iphoneos \
                   -configuration Release \
                   clean build
      working-directory: taskii/ios

    - name: Archive the project
      run: |
        xcodebuild -workspace taskii/ios/<YourProjectName>.xcworkspace \
                   -scheme <YourSchemeName> \
                   -sdk iphoneos \
                   -configuration Release \
                   archive -archivePath taskii/ios/build/<YourProjectName>.xcarchive
      working-directory: taskii/ios

    - name: Export the IPA
      run: |
        xcodebuild -exportArchive \
                   -archivePath taskii/ios/build/<YourProjectName>.xcarchive \
                   -exportPath taskii/ios/build \
                   -exportOptionsPlist taskii/ios/ExportOptions.plist
      working-directory: taskii/ios
